"""Model-written chunk contexts for Module 5 Lesson 9 (contextual retrieval), written for the course by Claude.

Each context follows CONTEXT_PROMPT, Anthropic's contextual retrieval prompt, with the
whole document in view: that is how the method works, so no knowledge is withheld.
Contexts were written only for the internal registry documents (D01 to D15, 75 chunks);
the public Prometheus, Alertmanager and PostgreSQL chunks get the path header only.
Keys are "<doc_id>:<chunk number>".
"""

CONTEXT_PROMPT = ("<document>\n{document}\n</document>\nHere is the chunk we want to situate within the whole "
                  "document\n<chunk>\n{chunk}\n</chunk>\nPlease give a short succinct context to situate this chunk "
                  "within the overall document for the purposes of improving search retrieval of the chunk. "
                  "Answer only with the succinct context and nothing else.")

CONTEXTS = {
    "D01:0": "From the Registry API reference: an overview of the registry service that stores every agent's configuration (name, model, tier, owner, status).",
    "D01:1": "From the Registry API reference: how requests authenticate to the registry with a registry key in the X-Registry-Key header, and the errors for a missing or unknown key.",
    "D01:2": "From the Registry API reference: how to list agents with GET /agents, paging through results with limit, cursor and next_cursor.",
    "D01:3": "From the Registry API reference: how to read a single agent's record with GET /agents/{agent_id}, including GET /agents/me for the agent that owns the calling key.",
    "D01:4": "From the Registry API reference: how to create an agent in the registry with POST /agents, which needs a write-scoped registry key.",
    "D01:5": "From the Registry API reference: how to change an agent's model, tier, owner or status with PATCH /agents/{agent_id}, which needs a write-scoped registry key.",
    "D01:6": "From the Registry API reference: how to delete an agent with DELETE /agents/{agent_id}, and why retiring an agent is preferred.",
    "D01:7": "From the Registry API reference: the registry's tiers (standard and priority) and which models each tier allows an agent to use.",
    "D01:8": "From the Registry API reference: the registry's rate limit per registry key, and the REG-1009 error returned when a key goes over it.",
    "D01:9": "From the Registry API reference: the shape of registry error responses, with REG-1007 MODEL_NOT_ALLOWED as the example, and a pointer to the error code reference.",
    "D02:0": "From the registry error code reference: authentication errors REG-1001 to REG-1004, for missing, invalid and revoked registry keys and keys without write scope.",
    "D02:1": "From the registry error code reference: request errors REG-1005 to REG-1008 and REG-1010, including agent not found, name taken, model not allowed on the tier, invalid fields and the deprecated claude-legacy model.",
    "D02:2": "From the registry error code reference: rate-limit and availability errors, REG-1009 RATE_LIMITED and REG-1011 for maintenance mode.",
    "D02:3": "From the registry error code reference: monitoring error codes MON-2001 and MON-2002, reported by the monitoring service when it can't scrape agents or reach the Registry API.",
    "D03:0": "From the registry changelog: release v2.6 (August 2026), which added GET /agents/me and maintenance mode.",
    "D03:1": "From the registry changelog: release v2.5 (July 2026), which deprecated the claude-legacy model and set its switch-off date.",
    "D03:2": "From the registry changelog: release v2.4 (May 2026), which lowered the registry rate limit to 60 requests per minute per key and added Retry-After.",
    "D03:3": "From the registry changelog: release v2.3 (March 2026), which added agent tiers and per-tier model allowlists.",
    "D03:4": "From the registry changelog: release v2.2 (January 2026), which added cursor-based paging to GET /agents.",
    "D04:0": "From the agent platform architecture overview: what the platform is and how agents use the registry, shared services and monitoring.",
    "D04:1": "From the agent platform architecture overview: the core services (registry-api, registry-db, auth-service, kb-search, monitoring) and the team that owns each.",
    "D04:2": "From the agent platform architecture overview: how a registry request flows through auth-service and registry-db, and what fails when each is slow or down.",
    "D04:3": "From the agent platform architecture overview: which agents (support_agent, triage_agent) depend on which services.",
    "D04:4": "From the agent platform architecture overview: which team to page for each core service.",
    "D05:0": "From the runbook for an agent latency spike: when to use it, including what the AgentLatencyHigh alert means.",
    "D05:1": "From the runbook for an agent latency spike, step 1: confirm the latency rise on the agent's dashboard before acting.",
    "D05:2": "From the runbook for an agent latency spike, step 2: find which tool or model call in slow sessions is causing the latency.",
    "D05:3": "From the runbook for an agent latency spike, step 3: check the search cache hit rate, which shows whether the cache was flushed.",
    "D05:4": "From the runbook for an agent latency spike, step 4: check the agent's logs for REG-1009 rate-limiting from the registry.",
    "D05:5": "From the runbook for an agent latency spike, step 5: escalate to the owning team, and why not to restart a slow agent.",
    "D06:0": "From the runbook for rotating an agent's registry key: when to rotate, on schedule and immediately if the key may have been exposed.",
    "D06:1": "From the runbook for rotating an agent's registry key, step 1: issue a new key with regctl while the old key keeps working.",
    "D06:2": "From the runbook for rotating an agent's registry key, step 2: deploy the new key to the agent.",
    "D06:3": "From the runbook for rotating an agent's registry key, step 3: verify the newly deployed key with GET /agents/me.",
    "D06:4": "From the runbook for rotating an agent's registry key, step 4: revoke the old registry key, and how long the old and new keys may both stay valid.",
    "D07:0": "From the runbook for migrating agents off claude-legacy: why the model is deprecated and the date it is switched off.",
    "D07:1": "From the runbook for migrating agents off claude-legacy: which agents still use claude-legacy and the model each should move to.",
    "D07:2": "From the runbook for migrating agents off claude-legacy, step 1: check the target model is allowed on the agent's tier.",
    "D07:3": "From the runbook for migrating agents off claude-legacy, step 2: compare the target model's output before switching.",
    "D07:4": "From the runbook for migrating agents off claude-legacy, step 3: switch the agent's model with PATCH.",
    "D07:5": "From the runbook for migrating agents off claude-legacy, step 4: what to do if the new model misbehaves, since rolling back to claude-legacy isn't possible.",
    "D08:0": "From the monitoring guide: what monitoring collects for each agent, and how it learns the agent list by polling the registry.",
    "D08:1": "From the monitoring guide: the alerts (AgentLatencyHigh, AgentErrorRateHigh, RegistryUnreachable) and when each fires.",
    "D08:2": "From the monitoring guide: what to do when the RegistryUnreachable alert fires, and why dashboards may show no agents.",
    "D08:3": "From the monitoring guide: the agent dashboards, what they show and how often they refresh.",
    "D08:4": "From the monitoring guide: how often your own dashboards should poll the registry, and the rate limit they share.",
    "D09:0": "Summary of incident INC-2041: billing_agent couldn't issue invoices for over two hours because payments-gateway timed out.",
    "D09:1": "Timeline of incident INC-2041 (billing_agent unable to issue invoices), from the first AgentErrorRateHigh alert to recovery.",
    "D09:2": "Root cause of incident INC-2041: an expired intermediate certificate in auth-service made payments-gateway time out for billing_agent.",
    "D09:3": "What changed after incident INC-2041 (expired auth-service certificate): certificate expiry alerts, fail-fast payments-gateway, capped retries.",
    "D10:0": "Summary of incident INC-2067: research_agent answered from outdated knowledge-base articles for a week, noticed by a user.",
    "D10:1": "What happened in incident INC-2067: a kb-search cache time-to-live set to 7 days instead of 7 hours made research_agent return stale results.",
    "D10:2": "Incident INC-2067 (research_agent stale results): why monitoring didn't catch it and it took a week to notice.",
    "D10:3": "What changed after incident INC-2067 (kb-search stale cache): reviewed cache settings and dated search results.",
    "D11:0": "Summary of incident INC-2093: a 42-minute registry outage while registry-db failed over to its standby.",
    "D11:1": "Timeline of incident INC-2093 (registry outage during database failover), from the registry-db disk check failure to recovery.",
    "D11:2": "Incident INC-2093 (registry outage during database failover): why the failover took 42 minutes, standby replication lag with no alert.",
    "D11:3": "What changed after incident INC-2093 (registry outage): a standby lag alert, monitoring keeping its last agent list, and support_agent's user message.",
    "D12:0": "Summary of security postmortem SEC-014: support_agent's write-scoped registry key was found in plain text in its debug logs and rotated.",
    "D12:1": "Security postmortem SEC-014: how support_agent's registry key came to be written to its logs, via REGISTRY_DEBUG.",
    "D12:2": "What changed after security postmortem SEC-014 (registry key in logs): masking keys in logs, auto-expiring debug mode, log review.",
    "D13:0": "From billing_agent's spend limits page: its monthly spending cap and what happens at 80% and 100% of it.",
    "D13:1": "From billing_agent's spend limits page: how to request a higher monthly spending cap and who approves it.",
    "D13:2": "From billing_agent's spend limits page: why the spending cap exists, after a retry loop bug in March.",
    "D14:0": "From the agent owners' FAQ: what to check when an agent suddenly stops answering.",
    "D14:1": "From the agent owners' FAQ: whether an agent can use the biggest model, which depends on its tier.",
    "D14:2": "From the agent owners' FAQ: how to find which model an agent is on, including from code running as the agent.",
    "D14:3": "From the agent owners' FAQ: why an agent gets rate-limited by the registry when it shares a registry key.",
    "D14:4": "From the agent owners' FAQ: who to ask about an agent's costs and spending caps.",
    "D14:5": "From the agent owners' FAQ: why an agent still behaves the old way after its settings change.",
    "D15:0": "The title of the on-call tips wiki page, which anyone in the company can edit.",
    "D15:1": "From the on-call tips wiki page: reading the dashboards during an incident, and what a blank dashboard usually means.",
    "D15:2": "From the on-call tips wiki page: what to do when an agent gets REG-1003 errors after a registry key rotation.",
    "D15:3": "From the on-call tips wiki page: how to page another team during an incident.",
    "D15:4": "From the on-call tips wiki page: quiet hours, and which alerts page at night.",
}
