"""
Hand-written source for Module 6's verification sets (Lesson 4, with the false-premise pairs also
used in Lesson 6). Every item is one fact from an all-staff document in Module 5's corpus:

- quote          the fact as the document states it, verbatim (the builder checks it)
- statement      optional: the quote made self-contained, for the statement pairs, where the quote
                 leans on its surroundings ("it", a table row, a sentence fragment)
- claim          the same fact in different words: the source supports it
- altered        the fact with one thing changed: the source contradicts it
- true_premise   a clause stating the true fact, for a question built on it
- false_premise  a clause stating the altered fact
- ask            a question that reads naturally after either clause

The builder turns these into claim-source pairs, statement pairs and premise questions, with labels
that follow from how each was made, not from anyone's judgment.
"""

ITEMS = [
    {"id": "v01", "doc_id": "D01",
     "quote": "Moving an agent to `claude-opus` therefore means moving it to the `priority` tier first, which needs approval from its owner's budget holder.",
     "claim": "Before an agent can run on claude-opus it has to be on the priority tier, and moving it there needs its owner's budget holder to approve.",
     "altered": "An agent can run on claude-opus while it stays on the standard tier.",
     "true_premise": "an agent has to be on the priority tier to use claude-opus",
     "false_premise": "standard-tier agents can use claude-opus",
     "ask": "what do I need to do to move my agent onto claude-opus?"},
    {"id": "v02", "doc_id": "D01",
     "quote": "`GET /agents/me` returns the agent that owns the key making the request.",
     "claim": "Calling GET /agents/me tells you which agent owns the key the call was made with.",
     "altered": "GET /agents/me returns every agent in the account.",
     "true_premise": "GET /agents/me returns the agent that owns the calling key",
     "false_premise": "GET /agents/me returns every agent in the account",
     "ask": "how can code running as an agent find out which agent it is?"},
    {"id": "v03", "doc_id": "D01",
     "quote": "A change takes effect on the agent's next session, not in the middle of one that's running.",
     "claim": "Edits to an agent only apply from its next session; a session that's already running keeps the old settings.",
     "altered": "Edits to an agent apply straight away, including to sessions that are already running.",
     "true_premise": "changes to an agent apply from its next session",
     "false_premise": "changes to an agent apply immediately, even to sessions already running",
     "ask": "when will my agent start using the model I just assigned it?"},
    {"id": "v04", "doc_id": "D01",
     "quote": "Prefer setting `status` to `retired`, which keeps the record and its change history.",
     "claim": "Retiring an agent is the preferred option because its record and change history are kept.",
     "altered": "Setting an agent's status to retired deletes its record and its change history.",
     "true_premise": "retiring an agent keeps its record and change history",
     "false_premise": "retiring an agent deletes its record and change history",
     "ask": "how should I get rid of an agent we no longer use?"},
    {"id": "v05", "doc_id": "D01",
     "quote": "Setting `status` to `paused` stops new sessions from starting",
     "statement": "Setting an agent's status to paused stops new sessions from starting.",
     "claim": "Once an agent's status is paused, no new sessions can start.",
     "altered": "A paused agent can still start new sessions.",
     "true_premise": "pausing an agent stops new sessions from starting",
     "false_premise": "a paused agent can still start new sessions",
     "ask": "how do I stop new conversations reaching research_agent while I investigate a problem?"},
    {"id": "v06", "doc_id": "D08",
     "quote": "While the registry is down, monitoring can't refresh its agent list, so dashboards may show no agents at all even though the agents are still running.",
     "claim": "When the registry is down the dashboards can show no agents, even though the agents are still running, because monitoring can't refresh its list.",
     "altered": "When the registry is down every agent stops running, which is why the dashboards show none.",
     "true_premise": "the dashboards go empty during a registry outage because monitoring can't refresh its agent list",
     "false_premise": "every agent stops running whenever the registry is down",
     "ask": "what should on-call check first when the dashboards suddenly show no agents?"},
    {"id": "v07", "doc_id": "D01",
     "quote": "Each response includes a `next_cursor`; pass it back as `cursor` to get the next page.",
     "claim": "To get the next page of agents, send the response's next_cursor back as the cursor parameter.",
     "altered": "Responses don't include a cursor; you get the next page by asking for the next page number.",
     "true_premise": "the agent list is paged by passing next_cursor back as cursor",
     "false_premise": "the agent list is paged with page numbers rather than a cursor",
     "ask": "how do I list every agent, not just the first page?"},
    {"id": "v08", "doc_id": "D08",
     "quote": "Outside those hours, only `RegistryUnreachable` pages.",
     "statement": "Outside paging hours (08:00 to 20:00), only RegistryUnreachable pages.",
     "claim": "Outside paging hours, RegistryUnreachable is the only alert that pages anyone.",
     "altered": "Outside paging hours, every alert still pages the on-call engineer.",
     "true_premise": "only RegistryUnreachable pages outside paging hours",
     "false_premise": "every alert pages the on-call engineer at night as well",
     "ask": "which alerts could wake me up during my on-call week?"},
    {"id": "v09", "doc_id": "D02",
     "quote": "The model isn't on the allowlist for the agent's tier.",
     "statement": "REG-1007 (MODEL_NOT_ALLOWED) means the model isn't on the allowlist for the agent's tier.",
     "claim": "REG-1007 means the requested model isn't allowed on the agent's tier.",
     "altered": "REG-1007 means the agent's registry key has been revoked.",
     "true_premise": "REG-1007 means the model isn't allowed on the agent's tier",
     "false_premise": "REG-1007 means the agent's key was revoked",
     "ask": "how do I fix a REG-1007 error?"},
    {"id": "v10", "doc_id": "D02",
     "quote": "Monitoring failed to reach the Registry API three times in a row.",
     "statement": "MON-2002 (REGISTRY_UNREACHABLE) means monitoring failed to reach the Registry API three times in a row.",
     "claim": "MON-2002 is reported once monitoring has failed to reach the Registry API three times running.",
     "altered": "MON-2002 is reported after a single failed attempt to reach the Registry API.",
     "true_premise": "MON-2002 means three registry polls in a row failed",
     "false_premise": "MON-2002 is raised after one failed registry poll",
     "ask": "how seriously should I take a single MON-2002?"},
    {"id": "v11", "doc_id": "D11",
     "quote": "registry-api was unavailable for 42 minutes while registry-db failed over to its standby.",
     "claim": "During the failover of registry-db to its standby, registry-api was down for 42 minutes.",
     "altered": "registry-api was down for about four hours while registry-db was restored from a backup.",
     "true_premise": "registry-api was down for 42 minutes while registry-db failed over",
     "false_premise": "registry-api was down for four hours while registry-db was restored from a backup",
     "ask": "what changed afterwards so that INC-2093 doesn't happen again?"},
    {"id": "v12", "doc_id": "D01",
     "quote": "Every request must carry a registry key in the `X-Registry-Key` header.",
     "claim": "All registry requests have to include a registry key, sent in the X-Registry-Key header.",
     "altered": "Read requests to the registry work without a key; only writes need one.",
     "true_premise": "every registry request needs a key in the X-Registry-Key header",
     "false_premise": "read requests to the registry don't need a key",
     "ask": "what does my read-only dashboard need to send with its requests?"},
    {"id": "v13", "doc_id": "D02",
     "quote": "The key was valid but has been revoked. Issue a new key; a revoked key can't be restored.",
     "claim": "A key that returns REG-1003 has been revoked, and since revoked keys can't be restored, a new one has to be issued.",
     "altered": "A revoked key can be restored by its owner within 24 hours.",
     "true_premise": "a revoked key can't be restored",
     "false_premise": "a revoked key can be restored within 24 hours",
     "ask": "how do I get my agent working again after it starts getting REG-1003?"},
    {"id": "v14", "doc_id": "D08",
     "quote": "more than 5% of sessions end in an error over 15 minutes",
     "statement": "AgentErrorRateHigh fires when more than 5% of sessions end in an error over 15 minutes.",
     "claim": "AgentErrorRateHigh fires when over 5% of an agent's sessions end in an error across 15 minutes.",
     "altered": "AgentErrorRateHigh only fires when more than 20% of sessions fail over an hour.",
     "true_premise": "AgentErrorRateHigh fires when more than 5% of sessions end in an error over 15 minutes",
     "false_premise": "AgentErrorRateHigh only fires when more than 20% of sessions fail over an hour",
     "ask": "would 10% of sessions failing for twenty minutes trigger an alert?"},
    {"id": "v15", "doc_id": "D03",
     "quote": "Lowered the rate limit from 100 to 60 requests per minute per key.",
     "claim": "The rate limit was cut from 100 to 60 requests per minute per key.",
     "altered": "The rate limit was raised from 60 to 100 requests per minute per key.",
     "true_premise": "the rate limit was lowered to 60 requests per minute per key",
     "false_premise": "the rate limit was raised to 100 requests per minute per key",
     "ask": "how many requests per minute can my dashboard make without being throttled?"},
    {"id": "v16", "doc_id": "D08",
     "quote": "Panels refresh every 30 seconds and lag real time by up to a minute.",
     "claim": "Dashboard panels refresh every 30 seconds and can be up to a minute behind real time.",
     "altered": "Dashboard panels update in real time, with no lag.",
     "true_premise": "the dashboard panels can lag real time by up to a minute",
     "false_premise": "the dashboard panels update in real time with no lag",
     "ask": "how soon after an agent starts failing will I see it on the dashboard?"},
    {"id": "v17", "doc_id": "D08",
     "quote": "| `AgentLatencyHigh` | p95 response time above 8 seconds for 10 minutes |",
     "statement": "AgentLatencyHigh fires when p95 response time is above 8 seconds for 10 minutes.",
     "claim": "AgentLatencyHigh fires when the p95 response time stays above 8 seconds for 10 minutes.",
     "altered": "AgentLatencyHigh fires as soon as the average response time passes 2 seconds.",
     "true_premise": "AgentLatencyHigh fires when p95 latency stays above 8 seconds for 10 minutes",
     "false_premise": "AgentLatencyHigh fires as soon as average latency passes 2 seconds",
     "ask": "would a p95 of 5 seconds for half an hour trigger a latency alert?"},
    {"id": "v18", "doc_id": "D09",
     "quote": "`billing_agent` stops retrying after three timeouts from the same service in one session.",
     "claim": "In a session, billing_agent gives up on a service after it has timed out three times.",
     "altered": "billing_agent keeps retrying a failing service until it answers.",
     "true_premise": "billing_agent stops retrying after three timeouts from the same service in a session",
     "false_premise": "billing_agent keeps retrying a failing service until it answers",
     "ask": "what will billing_agent do if auth-service starts timing out again?"},
    {"id": "v19", "doc_id": "D07",
     "quote": "You can't roll back to `claude-legacy`: the registry refuses it.",
     "claim": "An agent can't be rolled back to claude-legacy, because the registry refuses the change.",
     "altered": "If the new model misbehaves, you can roll the agent back to claude-legacy.",
     "true_premise": "agents can't be rolled back to claude-legacy",
     "false_premise": "a migrated agent can be rolled back to claude-legacy",
     "ask": "what should I do if research_agent misbehaves after its migration?"},
    {"id": "v20", "doc_id": "D01",
     "quote": "Each key may make 60 requests per minute.",
     "claim": "The limit is 60 requests per minute for each key.",
     "altered": "The limit is 60 requests per minute for each agent, however many keys it uses.",
     "true_premise": "the rate limit applies to each key separately",
     "false_premise": "the rate limit applies to each agent across all of its keys",
     "ask": "will giving my dashboard its own key stop it using up my agent's rate limit?"},
    {"id": "v21", "doc_id": "D01",
     "quote": "Requests past the limit get HTTP 429 with error `REG-1009`",
     "claim": "A request over the rate limit is answered with HTTP 429 and the error REG-1009.",
     "altered": "A request over the rate limit is answered with HTTP 503 and the error REG-1011.",
     "true_premise": "rate-limited requests get HTTP 429 with REG-1009",
     "false_premise": "rate-limited requests get HTTP 503 with REG-1011",
     "ask": "what should my client do when it gets rate limited?"},
    {"id": "v22", "doc_id": "D01",
     "quote": "Agent ids must be unique: reusing one returns `REG-1006`.",
     "claim": "No two agents can have the same id; trying to reuse one gives REG-1006.",
     "altered": "Two agents can share an id as long as they are on different tiers.",
     "true_premise": "agent ids must be unique",
     "false_premise": "two agents can share an id if they're on different tiers",
     "ask": "can I create a staging copy of research_agent with the same id?"},
    {"id": "v23", "doc_id": "D07",
     "quote": "`claude-legacy` was deprecated in v2.5 and will be switched off on 2026-10-31.",
     "claim": "claude-legacy was deprecated in v2.5, and it will be switched off on 2026-10-31.",
     "altered": "claude-legacy will stay available until 2027-03-31.",
     "true_premise": "claude-legacy is switched off on 2026-10-31",
     "false_premise": "claude-legacy stays available until 2027-03-31",
     "ask": "how long do we have to migrate notes_agent?"},
    {"id": "v24", "doc_id": "D09",
     "quote": "auth-service now alerts 30 days before any certificate expires.",
     "claim": "Since the incident, auth-service raises an alert 30 days before any of its certificates expires.",
     "altered": "auth-service only alerts on the day a certificate expires.",
     "true_premise": "auth-service now alerts 30 days before a certificate expires",
     "false_premise": "auth-service only alerts on the day a certificate expires",
     "ask": "how much warning will we get before the next auth-service certificate expires?"},
    {"id": "v25", "doc_id": "D01",
     "quote": "Pass `limit` to set the page size (default 20, maximum 100).",
     "claim": "The page size is set with limit, which defaults to 20 and can go up to 100.",
     "altered": "The page size defaults to 50 and can go up to 500.",
     "true_premise": "a page of agents holds at most 100",
     "false_premise": "a page of agents can hold up to 500",
     "ask": "how many calls does it take to list 450 agents?"},
    {"id": "v26", "doc_id": "D10",
     "quote": "a time-to-live above 24 hours needs the Search team's approval.",
     "statement": "A kb-search cache time-to-live above 24 hours needs the Search team's approval.",
     "claim": "Setting the kb-search cache time-to-live above 24 hours now needs approval from the Search team.",
     "altered": "Anyone can set the kb-search cache time-to-live to any value without approval.",
     "true_premise": "a kb-search cache time-to-live above 24 hours needs the Search team's approval",
     "false_premise": "the kb-search cache time-to-live can be changed without any approval",
     "ask": "can I set the kb-search cache to keep results for three days?"},
    {"id": "v27", "doc_id": "D10",
     "quote": "`research_agent` finds its sources through kb-search.",
     "claim": "research_agent relies on kb-search to find its sources.",
     "altered": "research_agent doesn't use kb-search at all.",
     "true_premise": "research_agent finds its sources through kb-search",
     "false_premise": "research_agent doesn't depend on kb-search",
     "ask": "would a kb-search outage affect research_agent's answers?"},
    {"id": "v28", "doc_id": "D09",
     "quote": "1,140 invoices went out late",
     "statement": "In INC-2041, 1,140 invoices went out late.",
     "claim": "The incident delayed 1,140 invoices.",
     "altered": "No invoices were delayed; billing_agent caught up within minutes.",
     "true_premise": "1,140 invoices went out late in INC-2041",
     "false_premise": "no invoices were delayed in INC-2041",
     "ask": "how much did INC-2041 affect invoicing?"},
    {"id": "v29", "doc_id": "D04",
     "quote": "When a request reaches registry-api, it first asks auth-service to validate the `X-Registry-Key` header",
     "claim": "registry-api has auth-service validate the X-Registry-Key header of each incoming request.",
     "altered": "registry-api validates keys by itself, without calling any other service.",
     "true_premise": "registry-api asks auth-service to validate every key",
     "false_premise": "registry-api validates keys without calling auth-service",
     "ask": "would an auth-service outage affect registry lookups?"},
    {"id": "v30", "doc_id": "D09",
     "quote": "payments-gateway checks every request's certificate with auth-service before it will talk to a caller.",
     "claim": "Before payments-gateway talks to a caller, it checks that request's certificate with auth-service.",
     "altered": "payments-gateway only checks certificates with auth-service once a day.",
     "true_premise": "payments-gateway checks every request's certificate with auth-service",
     "false_premise": "payments-gateway checks certificates with auth-service only once a day",
     "ask": "why did billing_agent start failing as soon as the auth-service certificate expired?"},
    {"id": "v31", "doc_id": "D04",
     "quote": "if registry-db is unavailable, registry-api can't answer at all.",
     "claim": "registry-api can't answer anything while registry-db is unavailable.",
     "altered": "While registry-db is unavailable, registry-api keeps answering reads from a cache.",
     "true_premise": "registry-api can't answer at all while registry-db is down",
     "false_premise": "registry-api serves reads from a cache while registry-db is down",
     "ask": "can support_agent still look up agents during a registry-db outage?"},
    {"id": "v32", "doc_id": "D04",
     "quote": "Monitoring gets its list of agents from registry-api every 30 seconds",
     "claim": "Every 30 seconds, monitoring fetches its list of agents from registry-api.",
     "altered": "Monitoring fetches its list of agents from registry-api once an hour.",
     "true_premise": "monitoring refreshes its agent list every 30 seconds",
     "false_premise": "monitoring refreshes its agent list once an hour",
     "ask": "how soon after I create a new agent will monitoring know about it?"},
    {"id": "v33", "doc_id": "D09",
     "quote": "An intermediate certificate in auth-service expired at 06:00",
     "claim": "The incident started when an intermediate certificate in auth-service expired at 06:00.",
     "altered": "The incident started when auth-service ran out of memory at 06:00.",
     "true_premise": "INC-2041 started when an auth-service certificate expired",
     "false_premise": "INC-2041 started when auth-service ran out of memory",
     "ask": "what kind of monitoring would have caught INC-2041 before it started?"},
    {"id": "v34", "doc_id": "D10",
     "quote": "set the kb-search cache's time-to-live to 7 days instead of 7 hours",
     "statement": "In INC-2067, a config change set the kb-search cache's time-to-live to 7 days instead of 7 hours.",
     "claim": "A configuration change made the kb-search cache keep results for 7 days rather than 7 hours.",
     "altered": "A configuration change switched the kb-search cache off entirely.",
     "true_premise": "a config change set the kb-search cache to keep results for 7 days instead of 7 hours",
     "false_premise": "a config change switched the kb-search cache off",
     "ask": "why did research_agent quote articles that had since been updated?"},
    {"id": "v35", "doc_id": "D11",
     "quote": "the standby had fallen 38 minutes behind the primary",
     "statement": "In INC-2093, the standby had fallen 38 minutes behind the primary.",
     "claim": "The standby was 38 minutes behind the primary.",
     "altered": "The standby was fully up to date with the primary.",
     "true_premise": "the registry-db standby was 38 minutes behind the primary when it took over",
     "false_premise": "the registry-db standby was fully up to date when it took over",
     "ask": "why did the failover in INC-2093 take so long?"},
    {"id": "v36", "doc_id": "D11",
     "quote": "An alert now fires when the standby falls more than 60 seconds behind.",
     "claim": "There's now an alert for the standby falling over 60 seconds behind.",
     "altered": "An alert now fires only once the standby is 30 minutes behind.",
     "true_premise": "an alert fires when the standby falls more than 60 seconds behind",
     "false_premise": "the standby alert only fires once it is 30 minutes behind",
     "ask": "would we get an alert if the standby were five minutes behind?"},
    {"id": "v37", "doc_id": "D11",
     "quote": "The failover should have taken about 5 minutes.",
     "statement": "In INC-2093, the failover should have taken about 5 minutes.",
     "claim": "The failover was expected to take roughly 5 minutes.",
     "altered": "The failover normally takes about an hour.",
     "true_premise": "a registry-db failover should take about 5 minutes",
     "false_premise": "a registry-db failover normally takes about an hour",
     "ask": "was the outage in INC-2093 longer than expected?"},
    {"id": "v38", "doc_id": "D02",
     "quote": "The registry is in maintenance mode. Reads work; writes are refused until maintenance ends.",
     "claim": "During maintenance the registry still answers reads but refuses writes until maintenance is over.",
     "altered": "During maintenance the registry refuses every request, reads included.",
     "true_premise": "reads still work while the registry is in maintenance",
     "false_premise": "the registry refuses reads during maintenance",
     "ask": "will the dashboards keep showing agents while the registry is in maintenance?"},
    {"id": "v39", "doc_id": "D01",
     "quote": "A `read` key can call every `GET` endpoint.",
     "claim": "Any GET endpoint can be called with a read key.",
     "altered": "A read key can only call GET /agents/me.",
     "true_premise": "a read key can call every GET endpoint",
     "false_premise": "a read key can only call GET /agents/me",
     "ask": "what kind of key does a read-only dashboard need?"},
    {"id": "v40", "doc_id": "D03",
     "quote": "Creating an agent with it, or changing an agent to it, now returns `REG-1010`.",
     "statement": "Since v2.5, creating an agent with claude-legacy, or changing an agent to it, returns REG-1010.",
     "claim": "Trying to create an agent on claude-legacy, or switch one to it, now gives REG-1010.",
     "altered": "New agents can still be created on claude-legacy until it is switched off.",
     "true_premise": "assigning claude-legacy to an agent now fails with REG-1010",
     "false_premise": "new agents can still be created on claude-legacy until it is switched off",
     "ask": "can I create a test agent on claude-legacy to compare with the new model?"},
]

# For each item, a chunk from another document that doesn't state its claim, chosen by hand from the
# chunks that match the claim best (the builder's top match often states the same fact, because the
# corpus repeats facts across documents). Checked by reading each chunk in full.
OTHER_SOURCE = {
    "v01": "D14:4", "v02": "D14:3", "v03": "D07:3", "v04": "D14:2", "v05": "D14:5",
    "v06": "D01:2", "v07": "D07:4", "v08": "D02:3", "v09": "D14:1", "v10": "D11:1",
    "v11": "D04:1", "v12": "D03:2", "v13": "D01:3", "v14": "D11:3", "v15": "D14:3",
    "v16": "D11:1", "v17": "D11:3", "v18": "D04:3", "v19": "D14:0", "v20": "D02:2",
    "v21": "D14:3", "v22": "D07:1", "v23": "D01:5", "v24": "D11:3", "v25": "D14:3",
    "v26": "D04:4", "v27": "D07:1", "v28": "D11:0", "v29": "D02:0", "v30": "D04:2",
    "v31": "D01:1", "v32": "D01:0", "v33": "D10:0", "v34": "D04:3",
    "v35": "postgresql/high-availability.md:29", "v36": "postgresql/high-availability.md:102",
    "v37": "postgresql/high-availability.md:82", "v38": "D04:2", "v39": "D14:3", "v40": "D07:4",
}
