"""
Set E: exact-answer questions for Module 6 (Reliability).

Written by hand in the content chat with the source documents in view. Each question has:
- four wordings: the first is the original, the other three say the same thing differently
- an answer that is a number or a short identifier, plus any other spellings accepted
- evidence: exact quotes from the corpus (checked by build-reliability-sets.py), which pick the gold chunks.
  A counting question quotes every table it counts across, so its context holds the whole list.
- for "step" questions, `check`: a Python expression over the evidence numbers that must equal the answer

kind is "lookup" (the answer is written in one place) or "step" (it needs a count, a sum, a
difference or a comparison). Numeric answers are asked for in a stated unit, so the answer is a
bare number.
"""

from datetime import date

QUESTIONS = [
    # ---- D01 Registry API reference ----
    dict(id="e01", kind="lookup", type="number", answer=20,
         evidence=[("D01", "Pass `limit` to set the page size (default 20, maximum 100).")],
         wordings=["How many agents does GET /agents return per page if you don't pass limit?",
                   "What is the default page size when listing agents?",
                   "If I call the agent listing endpoint without a limit, how many agents come back in one page?",
                   "When `limit` is left out of a GET /agents request, what page size does the registry use?"]),
    dict(id="e02", kind="lookup", type="number", answer=100,
         evidence=[("D01", "Pass `limit` to set the page size (default 20, maximum 100).")],
         wordings=["What is the largest page size GET /agents accepts?",
                   "What's the maximum value of limit when listing agents?",
                   "How many agents can I get back in a single page at most?",
                   "When paging through agents, what is the upper bound on the page size?"]),
    dict(id="e03", kind="lookup", type="text", answer="X-Registry-Key",
         evidence=[("D01", "Every request must carry a registry key in the `X-Registry-Key` header.")],
         wordings=["Which HTTP header carries the registry key?",
                   "What is the name of the header a request uses to send its registry key?",
                   "Where does the registry key go in a request? Give the header name.",
                   "To authenticate with the Registry API, which header do I set?"]),
    dict(id="e04", kind="lookup", type="text", answer="REG-1001",
         evidence=[("D01", "A request without one is rejected with `REG-1001`")],
         wordings=["What error code does the registry return when a request has no registry key?",
                   "Which error code means the registry key header was missing?",
                   "If I forget to send a key, what code comes back?",
                   "A call arrives with no X-Registry-Key header. Which error code does it get?"]),
    dict(id="e05", kind="lookup", type="text", answer="REG-1002",
         evidence=[("D01", "a key the registry doesn't recognise is rejected with `REG-1002`")],
         wordings=["What error code does the registry return for a key it doesn't recognise?",
                   "Which code means the key sent isn't one the registry knows?",
                   "If the key in the header is mistyped, which error code do I get?",
                   "An unrecognised registry key is rejected with which error code?"]),
    dict(id="e06", kind="lookup", type="text", answer="v2.6", accept=["2.6"],
         evidence=[("D01", "The current version is v2.6.")],
         wordings=["What is the current version of the Registry API?",
                   "Which Registry API version is current?",
                   "What version number is the registry API on now?",
                   "The Registry API reference describes which version as current?"]),
    dict(id="e07", kind="lookup", type="text", answer="REG-1006",
         evidence=[("D01", "Agent ids must be unique: reusing one returns `REG-1006`.")],
         wordings=["Which error code do you get when creating an agent with an id that already exists?",
                   "What error comes back if an agent_id is reused?",
                   "I tried to create an agent whose id is taken. What code did the registry return?",
                   "Creating a second agent with the same agent_id fails with which error code?"]),
    dict(id="e08", kind="lookup", type="text", answer="REG-1007",
         evidence=[("D01", "The model must be allowed on the agent's tier (see \"Tiers and models\"), or the request fails with `REG-1007`.")],
         wordings=["Which error code means the model isn't allowed on the agent's tier?",
                   "If I assign a model that the agent's tier doesn't permit, what error code do I get?",
                   "What code does the registry return for a model outside the tier's allowlist?",
                   "An agent on the standard tier is set to a model its tier doesn't allow. Which error code results?"]),
    dict(id="e09", kind="lookup", type="text", answer="REG-1004",
         evidence=[("D01", "It needs a `write` key; a `read` key gets `REG-1004`.")],
         wordings=["What error code does a read key get when it tries to PATCH an agent?",
                   "If I update an agent using a read-only key, which error code comes back?",
                   "Which code is returned when a key's scope doesn't allow a change?",
                   "A PATCH /agents request is made with a read key. What's the error code?"]),
    dict(id="e10", kind="lookup", type="text", answer="/agents/me", accept=["GET /agents/me"],
         evidence=[("D01", "`GET /agents/me` returns the agent that owns the key making the request.")],
         wordings=["Which endpoint returns the agent that owns the calling key?",
                   "What's the path for asking the registry which agent my key belongs to?",
                   "To check which agent a key belongs to, which endpoint should I call?",
                   "Name the registry endpoint that answers \"who am I?\" for the key making the request."]),
    dict(id="e11", kind="lookup", type="text", answer="2026-10-31",
         evidence=[("D01", "existing agents on it keep working until 2026-10-31.")],
         wordings=["Until what date do existing agents on claude-legacy keep working? Give the date as YYYY-MM-DD.",
                   "When is claude-legacy switched off? Answer in YYYY-MM-DD form.",
                   "What's the last date agents still on claude-legacy will run? Use the format YYYY-MM-DD.",
                   "On which date (YYYY-MM-DD) do agents on the deprecated claude-legacy model stop working?"]),
    dict(id="e12", kind="lookup", type="text", answer="priority",
         evidence=[("D01", "| `priority` | `claude-haiku`, `claude-sonnet`, `claude-opus` |")],
         wordings=["Which tier allows claude-opus?",
                   "An agent needs claude-opus. What tier does it have to be on?",
                   "On what tier can an agent use claude-opus?",
                   "claude-opus is only allowed on which tier?"]),
    dict(id="e13", kind="step", type="number", answer=3,
         evidence=[("D01", "| `priority` | `claude-haiku`, `claude-sonnet`, `claude-opus` |")],
         check="len(['claude-haiku', 'claude-sonnet', 'claude-opus'])",
         wordings=["How many models are allowed on the priority tier?",
                   "Count the models an agent on the priority tier may use.",
                   "What is the number of models on the priority tier's allowlist?",
                   "A priority-tier agent can choose from how many models?"]),
    dict(id="e14", kind="step", type="number", answer=2,
         evidence=[("D01", "| `standard` | `claude-haiku`, `claude-sonnet` |")],
         check="len(['claude-haiku', 'claude-sonnet'])",
         wordings=["How many models are allowed on the standard tier?",
                   "Count the models a standard-tier agent may use.",
                   "What is the number of models on the standard tier's allowlist?",
                   "A standard-tier agent can choose from how many models?"]),
    dict(id="e15", kind="lookup", type="text", answer="paused",
         evidence=[("D01", "Setting `status` to `paused` stops new sessions from starting")],
         wordings=["Which status value stops new sessions from starting but keeps the agent listed?",
                   "What status do I set to stop an agent starting new sessions without retiring it?",
                   "To stop new sessions while keeping the agent in the default listing, set status to what?",
                   "Which agent status prevents new sessions yet doesn't hide the agent from the default list?"]),
    dict(id="e16", kind="lookup", type="number", answer=429,
         evidence=[("D01", "Requests past the limit get HTTP 429 with error `REG-1009`")],
         wordings=["What HTTP status code does a rate-limited registry request get?",
                   "When a key goes over its per-minute limit, which HTTP status comes back?",
                   "Which HTTP status accompanies REG-1009?",
                   "A request past the rate limit is answered with which HTTP status code?"]),
    dict(id="e17", kind="lookup", type="text", answer="REG-1005",
         evidence=[("D01", "`GET /agents/{agent_id}` returns one agent's full record, or `REG-1005` if no agent has that id.")],
         wordings=["What error code does GET /agents/{agent_id} return when no agent has that id?",
                   "Which code means the agent id wasn't found?",
                   "If I look up an agent that doesn't exist, what error code do I get?",
                   "Fetching a nonexistent agent_id returns which error code?"]),

    # ---- D02 Error code reference ----
    dict(id="e18", kind="lookup", type="number", answer=422,
         evidence=[("D02", "| `REG-1007` | `MODEL_NOT_ALLOWED` | 422 |")],
         wordings=["Which HTTP status does REG-1007 come with?",
                   "What HTTP status code is returned with MODEL_NOT_ALLOWED?",
                   "REG-1007 is sent with which HTTP status?",
                   "What's the HTTP status for the error where a model isn't allowed on the tier?"]),
    dict(id="e19", kind="lookup", type="text", answer="KEY_REVOKED",
         evidence=[("D02", "| `REG-1003` | `KEY_REVOKED` | 401 |")],
         wordings=["What is the name of error REG-1003?",
                   "REG-1003 has which error name?",
                   "Give the error name that goes with code REG-1003.",
                   "Which named error is REG-1003?"]),
    dict(id="e20", kind="step", type="number", answer=3,
         evidence=[("D02", "| `REG-1001` | `MISSING_KEY` | 401 |"),
                   ("D02", "| `REG-1002` | `INVALID_KEY` | 401 |"),
                   ("D02", "| `REG-1003` | `KEY_REVOKED` | 401 |"),
                   ("D02", "| `REG-1005` | `AGENT_NOT_FOUND` | 404 |"),
                   ("D02", "| `REG-1009` | `RATE_LIMITED` | 429 |")],
         check="len(['REG-1001', 'REG-1002', 'REG-1003'])",
         wordings=["How many REG- error codes are returned with HTTP 401?",
                   "Count the registry error codes whose HTTP status is 401.",
                   "How many of the registry's error codes use status 401?",
                   "Of the REG- codes, how many come back as HTTP 401?"]),
    dict(id="e21", kind="step", type="number", answer=3,
         evidence=[("D02", "| `REG-1007` | `MODEL_NOT_ALLOWED` | 422 |"),
                   ("D02", "| `REG-1008` | `VALIDATION_FAILED` | 422 |"),
                   ("D02", "| `REG-1010` | `MODEL_DEPRECATED` | 422 |"),
                   ("D02", "| `REG-1001` | `MISSING_KEY` | 401 |"),
                   ("D02", "| `REG-1009` | `RATE_LIMITED` | 429 |")],
         check="len(['REG-1007', 'REG-1008', 'REG-1010'])",
         wordings=["How many REG- error codes are returned with HTTP 422?",
                   "Count the registry error codes whose HTTP status is 422.",
                   "How many of the registry's error codes use status 422?",
                   "Of the REG- codes, how many come back as HTTP 422?"]),
    dict(id="e22", kind="lookup", type="text", answer="REG-1011",
         evidence=[("D02", "| `REG-1011` | `REGISTRY_READ_ONLY` | 503 |")],
         wordings=["Which error code do writes get while the registry is in maintenance mode?",
                   "During registry maintenance, what error code is returned for a write?",
                   "What code means the registry is read-only for maintenance?",
                   "A PATCH sent during maintenance mode fails with which error code?"]),
    dict(id="e23", kind="lookup", type="number", answer=503,
         evidence=[("D02", "| `REG-1011` | `REGISTRY_READ_ONLY` | 503 |")],
         wordings=["What HTTP status comes with REG-1011?",
                   "Which HTTP status code does REGISTRY_READ_ONLY use?",
                   "REG-1011 is sent with which HTTP status?",
                   "During maintenance, refused writes get which HTTP status code?"]),
    dict(id="e24", kind="lookup", type="text", answer="MON-2002",
         evidence=[("D02", "| `MON-2002` | `REGISTRY_UNREACHABLE` |")],
         wordings=["Which monitoring error code means monitoring can't reach the Registry API?",
                   "What code does monitoring raise when the registry is unreachable?",
                   "Give the MON- code for REGISTRY_UNREACHABLE.",
                   "When monitoring repeatedly fails to reach the registry, which error code is it?"]),
    dict(id="e25", kind="lookup", type="number", answer=3,
         evidence=[("D02", "Monitoring failed to reach the Registry API three times in a row.")],
         wordings=["How many failed attempts in a row to reach the Registry API trigger MON-2002?",
                   "After how many consecutive failures does monitoring report MON-2002?",
                   "MON-2002 is raised after the registry is unreachable how many times running?",
                   "How many back-to-back failed registry polls does it take for MON-2002?"]),
    dict(id="e26", kind="step", type="number", answer=11,
         evidence=[("D02", "| `REG-1001` | `MISSING_KEY` | 401 |"),
                   ("D02", "| `REG-1005` | `AGENT_NOT_FOUND` | 404 |"),
                   ("D02", "| `REG-1009` | `RATE_LIMITED` | 429 |")],
         check="4 + 5 + 2",
         wordings=["How many REG- error codes does the error code reference list in total?",
                   "Count every registry (REG-) error code in the error code reference.",
                   "What is the total number of REG- codes documented?",
                   "Across all its tables, how many REG- codes does the error reference define?"]),

    # ---- D03 Registry changelog ----
    dict(id="e27", kind="lookup", type="text", answer="v2.5", accept=["2.5"],
         evidence=[("D03", "- Deprecated the `claude-legacy` model.")],
         wordings=["In which registry version was claude-legacy deprecated?",
                   "Which release of the registry deprecated claude-legacy?",
                   "What version number deprecated the claude-legacy model?",
                   "The claude-legacy deprecation shipped in which registry version?"]),
    dict(id="e28", kind="lookup", type="number", answer=100,
         evidence=[("D03", "Lowered the rate limit from 100 to 60 requests per minute per key.")],
         wordings=["According to the changelog, what was the per-key rate limit, in requests per minute, before v2.4?",
                   "Before the v2.4 change, how many requests per minute could a key make?",
                   "What rate limit (requests per minute per key) did v2.4 lower from?",
                   "The changelog says v2.4 lowered the rate limit. What was it before, in requests per minute?"]),
    dict(id="e29", kind="step", type="number", answer=40,
         evidence=[("D03", "Lowered the rate limit from 100 to 60 requests per minute per key.")],
         check="100 - 60",
         wordings=["By how many requests per minute did v2.4 lower the rate limit?",
                   "How much smaller, in requests per minute, was the rate limit after v2.4?",
                   "What was the size of the v2.4 rate-limit cut, in requests per minute?",
                   "v2.4 reduced the per-key limit by how many requests per minute?"]),
    dict(id="e30", kind="lookup", type="text", answer="2026-03-10",
         evidence=[("D03", "## v2.3 — 2026-03-10")],
         wordings=["When was registry v2.3 released? Give the date as YYYY-MM-DD.",
                   "What is the release date of v2.3? Answer in YYYY-MM-DD form.",
                   "On which date (YYYY-MM-DD) did v2.3 come out?",
                   "The v2.3 changelog entry is dated when? Use YYYY-MM-DD."]),
    dict(id="e31", kind="step", type="number", answer=122,
         evidence=[("D03", "## v2.5 — 2026-07-01"),
                   ("D03", "Agents already on `claude-legacy` keep running until 2026-10-31, when the model is switched off.")],
         check="(date(2026, 10, 31) - date(2026, 7, 1)).days",
         wordings=["How many days are there from the v2.5 release to the date claude-legacy is switched off?",
                   "Counting from the v2.5 release date, how many days until claude-legacy is switched off?",
                   "What is the number of days between v2.5's release and the claude-legacy switch-off date?",
                   "How long, in days, did owners get between v2.5 shipping and claude-legacy being switched off?"]),
    dict(id="e32", kind="lookup", type="text", answer="v2.6", accept=["2.6"],
         evidence=[("D03", "- Added `GET /agents/me`, which returns the agent that owns the calling key.")],
         wordings=["Which registry version added GET /agents/me?",
                   "In what version did the /agents/me endpoint appear?",
                   "GET /agents/me was introduced in which release?",
                   "Which changelog version first includes GET /agents/me?"]),
    dict(id="e33", kind="lookup", type="text", answer="offset",
         evidence=[("D03", "The `offset` parameter still works but is deprecated.")],
         wordings=["Which paging parameter was deprecated in v2.2?",
                   "What parameter of GET /agents still works but is deprecated since v2.2?",
                   "v2.2 introduced cursors. Which older parameter did it deprecate?",
                   "Name the deprecated parameter that cursor-based paging replaced."]),

    # ---- D04 Architecture overview ----
    dict(id="e34", kind="lookup", type="number", answer=30,
         evidence=[("D04", "Monitoring gets its list of agents from registry-api every 30 seconds")],
         wordings=["How often, in seconds, does monitoring fetch its list of agents from registry-api?",
                   "Every how many seconds does monitoring refresh the agent list from the registry?",
                   "What is the interval, in seconds, at which monitoring reads the agent list?",
                   "Monitoring pulls the agent list from registry-api once every how many seconds?"]),
    dict(id="e35", kind="lookup", type="text", answer="Identity", accept=["Identity team"],
         evidence=[("D04", "Owned by the Identity team.")],
         wordings=["Which team owns auth-service?",
                   "Who owns auth-service? Give the team name.",
                   "auth-service belongs to which team?",
                   "If auth-service breaks, which team owns it?"]),
    dict(id="e36", kind="lookup", type="text", answer="Search", accept=["Search team"],
         evidence=[("D04", "Owned by the Search team.")],
         wordings=["Which team owns kb-search?",
                   "Who owns kb-search? Give the team name.",
                   "kb-search belongs to which team?",
                   "If kb-search has a problem, which team owns it?"]),
    dict(id="e37", kind="lookup", type="text", answer="Postgres", accept=["PostgreSQL"],
         evidence=[("D04", "**registry-db** — the Postgres database behind registry-api")],
         wordings=["What kind of database is registry-db?",
                   "Which database system does registry-db run on?",
                   "registry-api stores its data in what database software?",
                   "Name the database engine behind registry-api."]),
    dict(id="e38", kind="step", type="number", answer=5,
         evidence=[("D04", "- **registry-api** — the Registry API."),
                   ("D04", "- **kb-search** — search over the internal knowledge base")],
         check="len(['registry-api', 'registry-db', 'auth-service', 'monitoring', 'kb-search'])",
         wordings=["How many core services does the architecture overview list?",
                   "Count the core services on the agent platform.",
                   "What is the number of core services described in the architecture overview?",
                   "The platform's core services section names how many services?"]),
    dict(id="e39", kind="step", type="number", answer=2,
         evidence=[("D04", "Stores every agent's configuration. Owned by the Platform team."),
                   ("D04", "with a hot standby for failover. Owned by the Platform team.")],
         check="len(['registry-api', 'registry-db'])",
         wordings=["How many of the core services does the Platform team own?",
                   "Count the core services owned by the Platform team.",
                   "The Platform team owns how many core services?",
                   "Of the platform's core services, how many belong to Platform?"]),

    # ---- D07 Migration runbook ----
    dict(id="e40", kind="step", type="number", answer=2,
         evidence=[("D07", "| `research_agent` | research-team | `claude-sonnet` |"),
                   ("D07", "| `notes_agent` | support-team | `claude-haiku` |")],
         check="len(['research_agent', 'notes_agent'])",
         wordings=["According to the migration runbook, how many active agents are on claude-legacy?",
                   "How many active agents does the migration runbook list as still on claude-legacy?",
                   "Count the active agents the runbook says need moving off claude-legacy.",
                   "The claude-legacy migration runbook names how many affected active agents?"]),
    dict(id="e41", kind="lookup", type="text", answer="claude-haiku",
         evidence=[("D07", "| `notes_agent` | support-team | `claude-haiku` |")],
         wordings=["Which model is notes_agent being migrated to?",
                   "What is the target model for notes_agent?",
                   "notes_agent moves off claude-legacy onto which model?",
                   "In the migration runbook, which model does notes_agent move to?"]),
    dict(id="e42", kind="lookup", type="number", answer=20,
         evidence=[("D07", "Run 20 recent tasks through the target model")],
         wordings=["How many recent tasks does the runbook say to run through the target model before switching?",
                   "Before switching models, how many recent tasks should you compare?",
                   "The migration runbook's comparison step uses how many recent tasks?",
                   "How many tasks does step 2 of the migration runbook ask you to run on the new model?"]),
    dict(id="e43", kind="lookup", type="text", answer="research-team",
         evidence=[("D07", "| `research_agent` | research-team | `claude-sonnet` |")],
         wordings=["Who owns research_agent?",
                   "Which team is the owner of research_agent?",
                   "research_agent belongs to which owner?",
                   "According to the migration runbook, what is research_agent's owner?"]),

    # ---- D08 Monitoring guide ----
    dict(id="e44", kind="lookup", type="number", answer=8,
         evidence=[("D08", "| `AgentLatencyHigh` | p95 response time above 8 seconds for 10 minutes |")],
         wordings=["Above what p95 response time, in seconds, does AgentLatencyHigh fire?",
                   "What is the p95 latency threshold for AgentLatencyHigh, in seconds?",
                   "AgentLatencyHigh fires when p95 response time goes above how many seconds?",
                   "How many seconds of p95 latency trips the AgentLatencyHigh alert?"]),
    dict(id="e45", kind="lookup", type="number", answer=10,
         evidence=[("D08", "| `AgentLatencyHigh` | p95 response time above 8 seconds for 10 minutes |")],
         wordings=["For how many minutes must p95 stay above the threshold before AgentLatencyHigh fires?",
                   "How long, in minutes, does latency have to stay high for AgentLatencyHigh?",
                   "AgentLatencyHigh needs the p95 threshold exceeded for how many minutes?",
                   "What duration, in minutes, does the AgentLatencyHigh condition have to hold?"]),
    dict(id="e46", kind="lookup", type="number", answer=5,
         evidence=[("D08", "| `AgentErrorRateHigh` | more than 5% of sessions end in an error over 15 minutes |")],
         wordings=["Above what percentage of sessions ending in error does AgentErrorRateHigh fire?",
                   "What error-rate percentage triggers AgentErrorRateHigh?",
                   "AgentErrorRateHigh fires when more than what percent of sessions error?",
                   "What is the error-rate threshold for AgentErrorRateHigh, as a percentage?"]),
    dict(id="e47", kind="step", type="number", answer=12,
         evidence=[("D08", "Alerts go to the on-call channel and page the on-call engineer between 08:00 and 20:00.")],
         check="20 - 8",
         wordings=["For how many hours of the day do all alerts page the on-call engineer?",
                   "How many hours a day is the paging window for every alert?",
                   "Every alert pages during a daily window. How many hours long is it?",
                   "How long, in hours, is the part of the day when any alert can page on-call?"]),
    dict(id="e48", kind="lookup", type="text", answer="RegistryUnreachable",
         evidence=[("D08", "Outside those hours, only `RegistryUnreachable` pages.")],
         wordings=["Which alert still pages outside 08:00 to 20:00?",
                   "At night, which is the only alert that pages?",
                   "Outside paging hours, which alert still wakes the on-call engineer?",
                   "Name the one alert that pages outside the daytime window."]),
    dict(id="e49", kind="lookup", type="number", answer=30,
         evidence=[("D08", "Panels refresh every 30 seconds and lag real time by up to a minute.")],
         wordings=["How often, in seconds, do dashboard panels refresh?",
                   "What is the refresh interval of the monitoring dashboard panels, in seconds?",
                   "Dashboard panels update every how many seconds?",
                   "Every how many seconds does a monitoring panel refresh?"]),

    # ---- D09 INC-2041 ----
    dict(id="e50", kind="lookup", type="number", answer=1140,
         evidence=[("D09", "1,140 invoices went out late")],
         wordings=["How many invoices went out late in INC-2041?",
                   "During the billing_agent incident, how many invoices were sent late?",
                   "INC-2041 delayed how many invoices?",
                   "What number of invoices were late because of INC-2041?"]),
    dict(id="e51", kind="step", type="number", answer=135,
         evidence=[("D09", "failed to issue invoices for 2 hours 15 minutes")],
         check="2 * 60 + 15",
         wordings=["How long, in minutes, was billing_agent unable to issue invoices in INC-2041?",
                   "In minutes, how long did INC-2041 last?",
                   "For how many minutes did billing_agent fail to issue invoices?",
                   "What was the duration of the INC-2041 outage, in minutes?"]),
    dict(id="e52", kind="step", type="number", answer=118,
         evidence=[("D09", "06:02 — `AgentErrorRateHigh` fired for `billing_agent`."),
                   ("D09", "08:00 — The on-call engineer saw the alert")],
         check="(8 * 60) - (6 * 60 + 2)",
         wordings=["In INC-2041, how many minutes passed between the alert firing and the on-call engineer seeing it?",
                   "How long, in minutes, did the INC-2041 alert go unseen?",
                   "From AgentErrorRateHigh firing to the engineer noticing, how many minutes elapsed in INC-2041?",
                   "What was the gap, in minutes, between the alert and the first human response in INC-2041?"]),
    dict(id="e53", kind="lookup", type="text", answer="Identity", accept=["Identity team"],
         evidence=[("D09", "The Identity team renewed the certificate.")],
         wordings=["Which team renewed the expired certificate in INC-2041?",
                   "In INC-2041, who renewed the certificate?",
                   "The certificate that caused INC-2041 was renewed by which team?",
                   "Which team fixed INC-2041 by renewing the certificate?"]),
    dict(id="e54", kind="lookup", type="number", answer=30,
         evidence=[("D09", "auth-service now alerts 30 days before any certificate expires.")],
         wordings=["After INC-2041, how many days before a certificate expires does auth-service now alert?",
                   "How much warning, in days, does auth-service now give before a certificate expires?",
                   "auth-service now alerts how many days ahead of certificate expiry?",
                   "Following INC-2041, the certificate-expiry alert fires how many days early?"]),
    dict(id="e55", kind="lookup", type="number", answer=3,
         evidence=[("D09", "`billing_agent` stops retrying after three timeouts from the same service in one session.")],
         wordings=["After how many timeouts from the same service does billing_agent now stop retrying?",
                   "How many timeouts in one session does billing_agent now tolerate before it stops retrying?",
                   "billing_agent gives up after how many timeouts from one service?",
                   "Since INC-2041, billing_agent stops retrying after how many timeouts?"]),
    dict(id="e56", kind="lookup", type="text", answer="06:00",
         evidence=[("D09", "An intermediate certificate in auth-service expired at 06:00")],
         wordings=["At what time did the intermediate certificate expire in INC-2041? Give it as HH:MM.",
                   "When (HH:MM) did auth-service's intermediate certificate expire?",
                   "What time, in HH:MM, did the certificate behind INC-2041 expire?",
                   "The expired certificate in INC-2041 ran out at what time? Use HH:MM."]),

    # ---- D10 INC-2067 ----
    dict(id="e57", kind="lookup", type="number", answer=7,
         evidence=[("D10", "set the kb-search cache's time-to-live to 7 days instead of 7 hours")],
         wordings=["In INC-2067, what time-to-live, in days, was the kb-search cache mistakenly set to?",
                   "How many days was the kb-search cache TTL set to by the bad config change?",
                   "The config change in INC-2067 set the cache time-to-live to how many days?",
                   "What wrong cache TTL, in days, caused INC-2067?"]),
    dict(id="e58", kind="step", type="number", answer=24,
         evidence=[("D10", "set the kb-search cache's time-to-live to 7 days instead of 7 hours")],
         check="(7 * 24) // 7",
         wordings=["In INC-2067, how many times longer was the mistaken cache time-to-live than the intended one?",
                   "The bad kb-search TTL was how many times the intended TTL?",
                   "By what factor did the INC-2067 config change multiply the cache time-to-live?",
                   "How many times longer than intended was the kb-search cache TTL during INC-2067?"]),
    dict(id="e59", kind="step", type="number", answer=7,
         evidence=[("D10", "From 2026-06-15 to 2026-06-22, `research_agent` answered questions")],
         check="(date(2026, 6, 22) - date(2026, 6, 15)).days",
         wordings=["How many days did INC-2067 last, counting from its start date to its end date?",
                   "What was the length of INC-2067 in days, from start date to end date?",
                   "From the first to the last date of INC-2067, how many days passed?",
                   "INC-2067 ran from one date to another. How many days apart are they?"]),
    dict(id="e60", kind="lookup", type="number", answer=24,
         evidence=[("D10", "a time-to-live above 24 hours needs the Search team's approval.")],
         wordings=["Above how many hours does a kb-search cache time-to-live now need approval?",
                   "What is the largest kb-search TTL, in hours, allowed without the Search team's approval?",
                   "A kb-search cache TTL above how many hours needs sign-off?",
                   "Since INC-2067, what TTL threshold in hours requires Search team approval?"]),
    dict(id="e61", kind="lookup", type="text", answer="kb-search",
         evidence=[("D10", "set the kb-search cache's time-to-live to 7 days instead of 7 hours")],
         wordings=["Whose cache was misconfigured in INC-2067? Give the service name.",
                   "Which service's cache caused research_agent's outdated results?",
                   "In INC-2067, the cache of which service had the wrong time-to-live?",
                   "Name the service whose cache setting broke research_agent in INC-2067."]),

    # ---- D11 INC-2093 ----
    dict(id="e62", kind="lookup", type="number", answer=42,
         evidence=[("D11", "registry-api was unavailable for 42 minutes")],
         wordings=["For how many minutes was registry-api unavailable in INC-2093?",
                   "How long, in minutes, was the registry down during INC-2093?",
                   "INC-2093 took registry-api offline for how many minutes?",
                   "What was the length of the INC-2093 registry outage, in minutes?"]),
    dict(id="e63", kind="lookup", type="number", answer=212,
         evidence=[("D11", "so 212 tickets queued")],
         wordings=["How many tickets queued during INC-2093?",
                   "In INC-2093, how many tickets did triage_agent fail to hand over?",
                   "How many tickets built up while the registry was down in INC-2093?",
                   "What number of tickets were stuck in the queue during INC-2093?"]),
    dict(id="e64", kind="lookup", type="number", answer=38,
         evidence=[("D11", "the standby had fallen 38 minutes behind the primary")],
         wordings=["How many minutes behind the primary was the standby in INC-2093?",
                   "By how many minutes had registry-db's standby fallen behind before INC-2093?",
                   "What was the standby's lag, in minutes, when the failover started?",
                   "In INC-2093, how far behind the primary was the standby, in minutes?"]),
    dict(id="e65", kind="lookup", type="number", answer=5,
         evidence=[("D11", "The failover should have taken about 5 minutes.")],
         wordings=["How many minutes should the INC-2093 failover have taken?",
                   "What was the expected duration of the registry-db failover, in minutes?",
                   "Normally, how long in minutes does a registry-db failover take, according to INC-2093?",
                   "The failover in INC-2093 was expected to take about how many minutes?"]),
    dict(id="e66", kind="step", type="number", answer=37,
         evidence=[("D11", "The failover should have taken about 5 minutes. It took 42")],
         check="42 - 5",
         wordings=["How many minutes longer than expected did the INC-2093 failover take?",
                   "By how many minutes did the INC-2093 failover overrun its expected duration?",
                   "The failover took longer than planned. How many extra minutes?",
                   "What was the difference, in minutes, between the expected and actual failover time in INC-2093?"]),
    dict(id="e67", kind="lookup", type="number", answer=60,
         evidence=[("D11", "An alert now fires when the standby falls more than 60 seconds behind.")],
         wordings=["After INC-2093, how many seconds of standby lag trigger an alert?",
                   "What standby lag, in seconds, now fires an alert?",
                   "The new replication-lag alert fires above how many seconds?",
                   "Since INC-2093, the standby may fall how many seconds behind before an alert fires?"]),
    dict(id="e68", kind="step", type="number", answer=32,
         evidence=[("D11", "14:20 — `support_agent` sessions began failing on their first registry lookup."),
                   ("D11", "14:52 — The standby finished catching up and registry-api recovered.")],
         check="52 - 20",
         wordings=["For how many minutes were support_agent sessions failing in INC-2093?",
                   "From when support_agent began failing to when the registry recovered, how many minutes passed?",
                   "How long, in minutes, did support_agent fail during INC-2093?",
                   "In INC-2093, what was the gap in minutes between support_agent's first failures and registry recovery?"]),
    dict(id="e69", kind="step", type="number", answer=13,
         evidence=[("D11", "14:52 — The standby finished catching up and registry-api recovered."),
                   ("D11", "The queued tickets were handed over by 15:05.")],
         check="(15 * 60 + 5) - (14 * 60 + 52)",
         wordings=["After registry-api recovered in INC-2093, how many minutes did it take to hand over the queued tickets?",
                   "How many minutes passed between recovery and the queued tickets being handed over?",
                   "Once the registry was back, how long in minutes did clearing the ticket queue take?",
                   "In INC-2093, what was the time in minutes from registry recovery to all tickets handed over?"]),

    # ---- across two incident reports ----
    dict(id="e70", kind="step", type="number", answer=177,
         evidence=[("D09", "failed to issue invoices for 2 hours 15 minutes"),
                   ("D11", "registry-api was unavailable for 42 minutes")],
         check="(2 * 60 + 15) + 42",
         wordings=["What is the combined duration, in minutes, of INC-2041 and INC-2093?",
                   "Add up the lengths of INC-2041 and INC-2093. How many minutes is that?",
                   "In total, how many minutes did INC-2041 and INC-2093 last?",
                   "How many minutes of outage did INC-2041 and INC-2093 cause together?"]),
    dict(id="e71", kind="step", type="text", answer="INC-2093",
         evidence=[("D09", "failed to issue invoices for 2 hours 15 minutes"),
                   ("D11", "registry-api was unavailable for 42 minutes")],
         check="'INC-2093' if 42 < 2 * 60 + 15 else 'INC-2041'",
         wordings=["Which incident was shorter, INC-2041 or INC-2093?",
                   "Between INC-2041 and INC-2093, which lasted less time?",
                   "Of INC-2041 and INC-2093, which one was over sooner?",
                   "Which had the shorter duration: INC-2041 or INC-2093?"]),

    # ---- Prometheus and Alertmanager documentation ----
    dict(id="e72", kind="lookup", type="number", answer=15,
         evidence=[("prometheus-server/storage.md", "the retention time defaults to `15d`")],
         wordings=["If no retention flag is set, how many days of data does Prometheus keep?",
                   "What is Prometheus's default retention time, in days?",
                   "By default, Prometheus retains samples for how many days?",
                   "With neither retention flag set, how long in days does Prometheus keep data?"]),
    dict(id="e73", kind="lookup", type="number", answer=2,
         evidence=[("prometheus-server/storage.md", "Ingested samples are grouped into two-hour blocks.")],
         wordings=["How many hours of samples does each of Prometheus's initial blocks cover?",
                   "Prometheus groups ingested samples into blocks of how many hours?",
                   "What is the length, in hours, of the blocks Prometheus first writes?",
                   "Newly ingested samples go into blocks spanning how many hours?"]),
    dict(id="e74", kind="lookup", type="number", answer=5,
         evidence=[("prometheus-server/querying/basics.md", "The lookback period is 5 minutes by default")],
         wordings=["What is Prometheus's default lookback period for queries, in minutes?",
                   "By default, how far back in minutes will a query look for a sample?",
                   "The query lookback delta defaults to how many minutes?",
                   "How many minutes is the default lookback period in PromQL?"]),
    dict(id="e75", kind="lookup", type="number", answer=30,
         evidence=[("alertmanager/configuration.md", "[ group_wait: <duration> | default = 30s ]")],
         wordings=["What is Alertmanager's default group_wait, in seconds?",
                   "By default, how many seconds does Alertmanager wait before the first notification for a new group?",
                   "group_wait defaults to how many seconds?",
                   "How long, in seconds, is Alertmanager's default group_wait?"]),
    dict(id="e76", kind="lookup", type="number", answer=4,
         evidence=[("alertmanager/configuration.md", "[ repeat_interval: <duration> | default = 4h ]")],
         wordings=["What is Alertmanager's default repeat_interval, in hours?",
                   "By default, after how many hours does Alertmanager resend a notification?",
                   "repeat_interval defaults to how many hours?",
                   "How long, in hours, is Alertmanager's default repeat_interval?"]),
    dict(id="e77", kind="step", type="number", answer=270,
         evidence=[("alertmanager/configuration.md", "[ group_wait: <duration> | default = 30s ]"),
                   ("alertmanager/configuration.md", "[ group_interval: <duration> | default = 5m ]")],
         check="5 * 60 - 30",
         wordings=["By default, how many seconds longer is Alertmanager's group_interval than its group_wait?",
                   "What is the difference, in seconds, between the default group_interval and the default group_wait?",
                   "How much longer, in seconds, is the default group_interval than the default group_wait?",
                   "Subtract Alertmanager's default group_wait from its default group_interval. How many seconds is that?"]),
    dict(id="e78", kind="lookup", type="number", answer=1,
         evidence=[("prometheus-docs/introduction/release-cycle.md", "receive selected bug fixes for an extended period of one year.")],
         wordings=["For how many years does a Prometheus LTS release receive selected bug fixes?",
                   "How long, in years, are Prometheus LTS releases supported?",
                   "A Prometheus LTS release gets bug fixes for how many years?",
                   "What is the support period of a Prometheus LTS release, in years?"]),
    dict(id="e79", kind="lookup", type="number", answer=6,
         evidence=[("prometheus-docs/introduction/release-cycle.md", "Every 6 weeks, a new Prometheus minor release cycle begins.")],
         wordings=["How many weeks long is a Prometheus minor release cycle?",
                   "A new Prometheus minor release cycle starts every how many weeks?",
                   "How often, in weeks, does Prometheus begin a minor release cycle?",
                   "What is the length of Prometheus's minor release cycle, in weeks?"]),
    dict(id="e80", kind="lookup", type="number", answer=512,
         evidence=[("prometheus-server/storage.md", "or more segment files, each up to 512 MB by default.")],
         wordings=["How large, in MB, can each chunk segment file in a Prometheus block be by default?",
                   "What is the default maximum size of a Prometheus chunk segment file, in MB?",
                   "By default, segment files in a block's chunks directory go up to how many MB?",
                   "In MB, what is the default size limit of each chunk segment file?"]),
    dict(id="e81", kind="lookup", type="number", answer=0,
         evidence=[("prometheus-docs/concepts/jobs_instances.md", "`1` if the instance is    healthy, i.e. reachable, or `0` if the scrape failed.")],
         wordings=["What value does the up series have when a scrape fails?",
                   "If Prometheus can't scrape an instance, what does up record for it?",
                   "The up time series is set to what number after a failed scrape?",
                   "What is the value of up for an unreachable instance?"]),
    dict(id="e82", kind="lookup", type="number", answer=7.0,
         evidence=[("prometheus-docs/introduction/release-cycle.md", "a CVSS rating of 7.0 or higher")],
         wordings=["What minimum CVSS rating must an issue have to be fixed in a Prometheus LTS release?",
                   "Prometheus LTS only fixes issues at or above which CVSS rating?",
                   "Which CVSS score is the threshold for LTS fixes?",
                   "An issue needs a CVSS rating of at least what to get an LTS fix?"]),
    dict(id="e83", kind="step", type="number", answer=1.5,
         evidence=[("prometheus-server/storage.md", "the retention time defaults to `15d`"),
                   ("prometheus-server/storage.md", "spanning up to 10% of the retention time, or 31 days, whichever is smaller.")],
         check="min(15 * 0.10, 31)",
         wordings=["With the default retention time, what is the longest span, in days, a compacted Prometheus block can cover?",
                   "At default retention, compaction can create blocks spanning at most how many days?",
                   "If retention is left at its default, how many days can a single compacted block span at most?",
                   "Using the default retention, what's the maximum time range, in days, of a compacted block?"]),
    dict(id="e84", kind="lookup", type="number", answer=5,
         evidence=[("alertmanager/configuration.md", "[ resolve_timeout: <duration> | default = 5m ]")],
         wordings=["What is Alertmanager's default resolve_timeout, in minutes?",
                   "resolve_timeout defaults to how many minutes?",
                   "By default, how many minutes is Alertmanager's resolve_timeout?",
                   "How long, in minutes, is the default resolve_timeout?"]),
]
